### ISSUE TITLE
Huawei Open submission data was cached on local SSDs

### ISSUE THREAD

**Issue by YardenMa** [mlcommons/hn7st6jxx77dbthjf9co#4]
Huawei’s OPEN submission utilized local SSDs on the benchmark hosts, with an aggregated capacity of 12TiB per node.

The submission indicates that 7 accelerators (H100, 3DUnet) were simulated per benchmark host. Each accelerator, on average, consumes 2.33TiB per benchmark run, based on the following calculation: Image size = 140M, Batch size = 7, 500 batches per epoch, and 5 epochs (140M * 7 * 500 * 5 = 2.33TiB). With 7 accelerators per node, each node would consume around 16TiB of data, excluding duplication. This setup allows approximately 75% of the data to be cached locally before the benchmark begins.
Since the benchmark always uses the same seed, the data sequence for each accelerator remains identical, which contrasts with real-world workloads that randomize data access. Additionally, in real life high-scale workloads, the same data might not be accessed twice, making caching meaningless.

According to Huawei's specifications, their OceanStore system has a total throughput of 6400Gb/s (32 x 200Gb/s), which equals 800GB/s. The reported 1TiB/s throughput can only be explained by using the local caches that were pre-fetched prior to the test run.
 
While the benchmark rules primarily mention DRAM caching, I believe this scenario is relevant as well.

**Comment by FileSystemGuy** [comment]
Here is my paraphrasing of a verbal discussion we had on Tuesday's review committee meeting concall.

The comment that "Since the benchmark always uses the same seed," is not completely accurate in that the benchmark does not always use the same seed, in fact it never sets the seed. The sequence of random numbers across all epochs of a given run for any given rank of the distributed training will come from a single random sequence, but the random sequence for each rank will be different, and all the random sequences for the next run will be different from this run.

From a storage perspective, if the contents of locally-attached SSD(s) are cache-coherent with the main (non-locally-attached) storage solution, then that is a (valuable) feature rather than any type of flaw. Eg: if the semantics of the storage solution is the same when running a distributed training task whether there are locally-attached SSD(s) or not, if it is only a performance difference and not a difference in behavior, then that is a feature. What could be argued is missing from Huawei's submission is something to show that the SSD-based caching is in fact semantically transparent to the application.

The Rules will be updated for v2.0 to be more clear about what types of “caching” are allowed and what types are not.

Given the grey-area of whether the SSDs in Huawei's product are directly under the complete control of their storage solution, ie: that they were a fully transparent caching layer managed by Oceanstore, I propose that we close this without action.  By "grey-area", I mean that I don't know the answer and Huawei is not in a position to tell us in the time available.

**Comment by wvaske** [comment]
There were discussions in the working group around caching solutions and we never really decided on how to handle them. Personally, I think they have their place given that Nvidia's DGX servers come preconfigured with the local NVMe configured as an NFS cache and Meta designed an entire caching layer (tectonic-shift) specifically for data-center scale caching of training data.

I think the local cache should be called out more prominently as part of the system name so that customers and industry professionals can clearly see that this system was benefiting from cacheable access sequences. But I do think it's a valid result and that the WG should explore whether specific rules are required for such systems.

--

Here's a comment I left on the other repo:
The files list staying the same per accelerator per epoch is likely a bug. The dlio code is supposed to generate a new randomly shuffled file list with a new seed to each accelerator on each epoch. It's the reconfigure function which calls build_sample_map_iter (https://github.com/argonne-lcf/dlio_benchmark/blob/bbe9bae59fc6afa40110bc3023ce9604480eb3e3/dlio_benchmark/utils/config.py#L317). If you look at that code, line 329 uses seed = "seed + epoch_number". We will need to address this in the WG meetings as I believe the behavior you've observed is not intended.

Whether data is reused is somewhat nuanced. Meta talks specifically about their DLRM model training which does not read data multiple times because it's so easy to just collect more data. Unet3D, Resnet, and Cosmoflow do not follow that same pattern as labelled data is harder to get. These models will do multiple epochs on the same datasets. Additionally, it's common for people running these benchmarks to pin a set of files to an individual accelerator specifically to enhance the cache hit rate. This would result in a design where each node should have enough local storage for their portion of the dataset and after the first epoch should have 100% cache hit rate.

An open submission is effectively able to break most of the rules. If this were a closed submission I'd be more concerned but since it's open I think this is showcasing the benefit of a caching system.

I am still open to changing my mind, but being an open submission I'm in favor of keeping the submission but VERY CLEARLY labeling this as a local-cache test. I do believe they have a place in the submissions but we need to be very clear that they do not really compete against the non-cached systems.

--

@Submitter: I would recommend modifying the system name to clearly articulate the size of the local cache in each node and what proportion of the node's addressable dataset would fit (so size of cache and cache:dataset ratio).

**Comment by YardenMa** [comment]
Hi, I will try to answer all at once.
 
Wes, I am glad you read the Tectonic-Shift article, I find it very informative, shedding light into how the hyper-scalers are running their huge workloads. As Meta’s solution is built on the use of cache, it is fundamentally different than what we see here.
Meta states in the article that real production, large-scale training jobs are not reading the same data twice. Instead, they run a single long epoch only reading each data sample once. For that reason, caching within single job is meaningless.
The entire Shift smart cache layer is built on parallel asynchronous jobs reading the same popular data. For this reason they have implemented a centralized cache that will be able to cache between different jobs.
In Huawei’s submission, data is cached on SSDs local to a GPU. Those GPUs are not likely going to run different training workloads based on data locality.
I agree that utilizing those local SSDs on the DGX servers is a good idea. Using those for fast checkpoints, or for some form of a hyper-converge system sounds like a good idea to me. Caching specific data is not reasonable for ML Training workloads due to the amount of data that’s being used on a real life workload, and the random access pattern.

Curtis, I apologize but my sentence is accurate. A seed is always set on the data sampler of the pytorch dataloader. In fact, the seed is also always the same and equals to 123.
image
![image](https://github.com/user-attachments/assets/8993f9cd-373c-473e-93b8-373e5808b66c)

To prove that the same data is always used, I ran 5 different runs on 2 nodes / 6 accelerators (H100,unet3d).
I logged the seed that was set for each rank and for each epoch. I also tweaked the code a bit so I can see which files are being accessed by which rank in each epoch. Everything, including the [code](https://github.com/VolumezTech/storage/tree/v1.0-data-sampling), [results](https://github.com/VolumezTech/storage/tree/v1.0-data-sampling/for-peer-review/full) and [parsing](https://github.com/VolumezTech/storage/blob/v1.0-data-sampling/for-peer-review/data_sampling.py) scripts are already available in our fork – feel free to verify me.

```
./data_sampling.py full 
running on dir full/run1
Rank 0: 12592 files
Rank 1: 12545 files
Rank 2: 12605 files
Rank 3: 12634 files
Rank 4: 12609 files
Rank 5: 12445 files
running on dir full/run2
Rank 0: 12592 files
Rank 1: 12545 files
Rank 2: 12605 files
Rank 3: 12634 files
Rank 4: 12609 files
Rank 5: 12445 files
running on dir full/run3
Rank 0: 12592 files
Rank 1: 12545 files
Rank 2: 12605 files
Rank 3: 12634 files
Rank 4: 12609 files
Rank 5: 12445 files
running on dir full/run4
Rank 0: 12592 files
Rank 1: 12545 files
Rank 2: 12605 files
Rank 3: 12634 files
Rank 4: 12609 files
Rank 5: 12445 files
running on dir full/run5
Rank 0: 12592 files
Rank 1: 12545 files
Rank 2: 12605 files
Rank 3: 12634 files
Rank 4: 12609 files
Rank 5: 12445 files
run 1 and 2 are identical
run 2 and 3 are identical
run 3 and 4 are identical
run 4 and 5 are identical
```
What happens in fact, that in the first run the indices are shuffled by the seed 123 for the first time. For each epoch after it is re-shuffled using the same seed, but the order is different because the starting point is different. Note that in my runs, the average files each rank sees are around 12.5k, summing up to an average capacity of around 1.668TiB. The more files the system has, this subset should grow towards 17.5k (a GPU is less likely to repeat the same file).  

As I see it, in the way the benchmark is built today, using local drives for cache is almost equivalent to running parallel benchmarks. Given a large enough SSD, any participant can “scale” their results based on the available budget and nothing else.

The caching was clearly done prior to the benchmark run, and not during the run, how else can you feed 1TB/s with a 800GB/s network? This is a clear transgression of section 2.6

> Under all circumstances, caching of training data on the host node(s) running MLPerf Storage before the benchmark begins is DISALLOWED.

**Comment by YardenMa** [comment]
Hi
 
I wanted to follow-up on our conversation from Friday and address some of the issues that were discussed.

> Storage system is allowed to warm up caches

Given that one cannot predict a random future, I am not sure how warming up the caches works. When you don’t know which data will be accessed from which GPU, you can’t pre-fetch the correct data. The best thing you can do is prefetch something and fill up the local disk with some of the samples.
 
On Huawei’s workload, they have ~183TB of data and  ~12TB of local disk capacity. This means that they could cache on each instance 6.5% of their data. With this prefetch policy, the results should improve by the same margin. Now let’s assume that Huawei has a magical cache system that predicts the future twice as better as randomly taking samples. We should be seeing an improvement by a margin of 13%.
 
In practice we see 7 Accelerators per node (instead of 5 for closed), which is a 40% improvement, and almost 50% when comparing raw bandwidth metrics. This does not seem realistic to me. It is a result of the data sequence being predictable.
 
I would also like to discuss the possibility that a data scientist will be using a semi-random data access pattern. This is still a random sequence, but it is predictable in the sense that the same sequence is always observed. You can prefetch that upfront, but as we know, models do not converge within 15 minutes of a benchmark run. During model training, much more data will be read, which will minimize the data repetition and cache hits (for a single GPU). The fact that most of the data can be cached on a local drive is a benchmark flaw that does not correlate to a real workload.

> It depends if the disks are under the control of OceanStore

Even if the data access predictability is not intentional, it is still very present. The fact a storage system may control the local disks does not matter, because we will never be able to differentiate manual caching and automated caching under the current conditions. Accepting this submission under those conditions severely reduces the benchmark’s credibility.

---
From our perspective, the current version of the rules does not allow this type of caching. 
My personal opinion is that if the working group wants to allow those types of systems, it should modify the rules accordingly for v2.0 . I will also recommend that those types of workloads will run on a different benchmark category, with modified conditions. First, those workloads should run a longer training job, that will consume more data (e.g larger epochs + more epochs). This will minimize the ability of participants to pre-fetch the test data upfront and will prove their cache system is the reason for the superior results. Second, the benchmark should ensure data access is not consistent between runs. Third, maybe the benchmark should set a limit to the local disk size, or change the required capacity accordingly.

**Comment by wvaske** [comment]
From the rules:

> On the other hand, we believed that repeated real-world training runs with a given storage system might benefit from caching in the storage system under normal circumstances, so we have not required cache invalidation there.

For me, here's the path:

1. Caching in the storage system is allowed (explicitly, see above)
2. Hyperconverged systems are allowed (explicitly, see definition of storage system access types)
3. The definition of host cache and storage system cache are different and we can't use the word "Cache" to always mean "host/client cache" (implicit)
4. Therefore, storage system cache that resides in the physical client/host is implicitly allowed as a form of hyperconvergence.

1 & 2 can't be argued. They're explicitly listed in the rules document.

3 is an implied due to the different language for host/client and storage system caches

To me, the natural conclusion is that the submission (which is allowed to break the caching rule by being an open submission) is acceptable for a CLOSED submission.

The rules explicitly call out that we expect data reuse in the individual job (most AI is not LLM or DLRM). 

It is common to pin datasets to specific accelerators (pytorch and tensorflow both have mechanisms to enable this). 

Using a characteristic of the benchmark to optimize performance is sort of the whole point of the benchmark and not against the rules or the spirit of the rules.


To me, the rules are extremely clear that nothing in this submission prevents Huawei from submitting in the CLOSED category. But that isn't even the question, it's submitted in OPEN which is very explicitly allowed to break rules of system configuration so long as the benchmark calculations are still the same and representing the same values.

**Comment by YardenMa** [comment]
Hi Wes – so that folks new to this thread can quickly grasp the issues, I’d like to sharpen the differences in our respective positions and addressing your items cited above:

> The rules explicitly call out that we expect data reuse in the individual job (most AI is not LLM or DLRM).It is common to pin datasets to specific accelerators (pytorch and tensorflow both have mechanisms to enable this).

We’ve been looking for use cases involving the practice of pinning data locally but are coming up short – do you have references for this practice? 
This is a key point around which many of the issues in this thread revolve:  perhaps pinning data is required because existing storage solutions are not fast enough to keep pace with the AI workload characteristics. **The aim of the benchmark is to enhance storage to fit AI; and not to bend AI to fit storage**.  Reducing randomization (via pinning data) is proved to extend overfitting and defeats the aim of the data scientist.

> To me, the natural conclusion is that the submission (which is allowed to break the caching rule by being an open submission) is acceptable for a CLOSED submission.

To me it is very clear that this workload is invalid based on the rules. The rules state:

> Under all circumstances, caching of training data on the host node(s) running MLPerf Storage before the benchmark begins is DISALLOWED. Caches in the host node(s) must be cleared between two consecutive benchmark runs.

I don’t know how this can be interpreted otherwise. Those host nodes are running the benchmark, and it is “**Under all circumstances … DISALLOWED**”.   Only Huawei has submitted this configuration, although many of us have the capabilities to run using a local SSD caching.  This is because that’s how all of us have interpreted the rules.
 
If this type of caching is valid, why is DRAM caching not allowed? What’s the difference between the two forms of caching?
 
The elephant in the room we need to address relevant to Huawei’s submission:  the “bug” that’s making the data pattern to be fully repeatable between test executions. In fact, for Huawei’s submission 75% of this data can reside on local disks, without requiring a smart cache. This is equivalent to separate systems for each benchmark host, **which is not allowed**.
 
This is not “Using a characteristic of the benchmark to optimize performance” -- on the contrary it benefits by “**taking advantage of a major bug to produce unrealistic results**”. This is the only submission that benefits from this bug since it uses cache.
 
I want to emphasize Huawei prefetched the data prior to the test run, either by running a benchmark run that was not documented, or by manually getting the files to the local disks (**which is not allowed**).  This is also the same as “cherry-picking” good results, **which is not allowed**.

Unfortunately, accepting these results contradicts the rules (which we all admit require further work, natural for an early benchmark) but will significantly diminish the benchmark credibility – especially to MLE practitioners.  The OPEN category would devolve into a throughput drag race, won by the biggest budgets.  No customer will be able to reproduce these results in a production environment.

**Comment by wvaske** [comment]
> I don’t know how this can be interpreted otherwise. Those host nodes are running the benchmark, and it is “Under all circumstances … DISALLOWED”.

Depends on the version of the rules you're reading.

Start at the github page for the storage repo:

https://github.com/mlcommons/storage

Scroll to the bottom and click Rules to get here:

https://github.com/mlcommons/storage/blob/main/Submission_guidelines.md

Section 2.6 in its entirety:
> 2.6. Caching
>Under all circumstances, caching of training data on the host node(s) running MLPerf Storage before the benchmark begins is DISALLOWED. Caches in the host node(s) must be cleared between two consecutive benchmark runs.

>On the one hand, we have sized the benchmark dataset to be 5x the size of DRAM on the host node(s) running the benchmark code so that the randomness of the access pattern can defeat any significant levels of caching in local DRAM. In that sense cache invalidation in the benchmark nodes should not be required, but out of an abundance of caution we do require it. On the other hand, we believed that repeated real-world training runs with a given storage system might benefit from caching in the storage system under normal circumstances, so we have not required cache invalidation there.

So yes, caching is disallowed but then the rules go into a section describing where things can be cached that don't need to be cleared. This implies that certain types of caching are allowed eventhough the statements are contradictory.

**Comment by FileSystemGuy** [comment]
Could you please provide a piece of information about your storage architecture?

The SSDs that were attached to the computer running the benchmark, were they directly and solely under the control of your software, or were they partially under software control and partially under manual control, or were they completely manually managed?

As I said in the other "issue", we are trying to understand what it is that you're intending to show off and why you thought that you could not submit in the CLOSED category.

The challenge for the peer review committee is outlined above.  The SSDs seemed to have a very high cache hit rate and we want to know how that came to be, how those SSDs were managed.

I recognize that this is a weekend, and that this request is very late in the process, but could you please respond with as much information as you can as quickly as you see this?  We have not seen any response(s) from you on the above and we'd very much like to see your information before we make a decision.

No action is requested from you except for providing information.

The deadline is approaching, and I apologize for the less-than-smooth experience you have had.  David Kanter tells me that the regulations here have recently changed and none of of will have to jump through these hoops again, thankfully.

**Comment by leoyanghw** [comment]
Please find below some additional details about the storage architecture used for our open submission.

To accelerate the training job, we implemented a prefetching system that uses the deterministic randomness of the shuffle to implement better caching for DL training. Examples of similar implementations that also use this technique include Quiver from FAST 2020, Why Globally Re-shuffle from IPDPS 2022, and Clairvoyant prefetching from SC 2021. Our solution takes advantage of this deterministic random feature of shuffle to prefetch part of the training data required by each GPU to the local SSD cache. Details can be found in the "run_benchmark.sh" script we added to the storage benchmark. This script uses functionality that is part of our storage product to load data into local SSDs and allow training data to be transparently read from the SSD when accessed, reducing the amount of data that needs to be loaded from the remote storage.

The local SSD cache space on the host is managed by our storage system. Other than adding the "run_benchmark.sh" script, the benchmark code is not modified. The benchmark does not know if data is cached, and the cache is transparent to client applications. There are no manual steps.

I think the key concern is if having the local SSD cache populated by the storage system violates the caching rules. Obviously, we thought it was non-violation at the time of submission. To avoid causing further confusion, we can withdraw our open submission. In version 2.0 of the storage benchmark, we recommend that the caching rules be more clearly defined, and that they better represent real-world production scenarios.

**Comment by johnb-volumez** [comment]
I think this is a mistake to accept this submission into any category.  It completely dilutes the intent and purpose of the benchmark.

The configuration does not actually use a predictive cache.  It just copies the data to the local SSD based upon MLPerf data access order.   Otherwise , the first epoch would have shown lower AU%.it looks like a static cache , not a dynamic one . 
 
It was submitted Open because they added a script to the code directory . looking at the script , there is no reason to include it in the code directory , it can be executed from anywhere else , just like the script we used to execute the benchmark . Hence , this submission can be submitted as Closed .
 
The SSDs in their architecture sit distinctly separately from the Oceanstore system and are not part of their storage system.  

 Curtis mentioned in the email and also at the WG meeting that there shouldn't be any manual control , but there is .
Their script will run a prepare stage on each benchmark host . they did not include the code for that , but as i understand it , the script will copy the data from the storage to each host according to its rank number
 
        full_command="$dataturbo_command rank_id=$rank_ids"
        echo "Executing data preparation command on host $host with rank_ids $rank_ids"
        echo "$full_command"
        ssh "$host" "$full_command" &
 
the full_command starts with preparedata command which they didn't disclose ( don't confuse the command with the function with the same name ) , and some benchmark parameters so it will know what to copy .
this is "manual control" ...
 
they also have a disclaimer at the run script:
###########################################################################################
# Our current test environment does not have a complete training and storage cluster,     #
# as well as the task scheduling module. Therefore, this demo script is used to simulate  #
# the data pre-loading and training process. It contains two steps. The first step        #
# is to preload data, and the second step is to invoke benchmark.sh provided by the       #
# MLPerf Storage benchmark to start training.                                             #
###########################################################################################
 
this shows that the data is preloaded

it looks this caching process they are using is tailored for the benchmark  ,i don't see how they incorporate it into the storage code
